# yaml-language-server: $schema=none

meta:
  title_template: "%s / DucNM"
  description: DucNM's Blog
  favicon: /favicon.svg

  # default author for blog entries
  author: Duc

site:
  origin: https://acme.org
  view_transitions: true

sitemap:
  enabled: true

rss:
  title: DucNM Blog
  collection: blog
  enabled: true

content:
  sections: true

collections:
  blog:
    include: [blog/]
    skip: [skip]
    sort: date desc

  projects:
    include: [blog/]
    skip: [skip]
    tags: [projects]
    sort: date desc

server:
  reload: true
